name: CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - uses: niden/actions-memcached@v7
      - run: npm ci
      - run: npm test
      - run: npm run lint
      - uses: primer/publish@v3.0.0
        with:
          default_branch: main
        env:
          GITHUB_TOKEN: ${{ github.token }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
